/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mcherubini;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** A weather media. */
@org.apache.avro.specific.AvroGenerated
public class WeatherMedia extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6898356123544780885L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WeatherMedia\",\"namespace\":\"com.mcherubini\",\"doc\":\"A weather media.\",\"fields\":[{\"name\":\"station\",\"type\":\"string\",\"order\":\"ignore\"},{\"name\":\"tempMedia\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WeatherMedia> ENCODER =
      new BinaryMessageEncoder<WeatherMedia>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WeatherMedia> DECODER =
      new BinaryMessageDecoder<WeatherMedia>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WeatherMedia> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WeatherMedia> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WeatherMedia> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<WeatherMedia>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WeatherMedia to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WeatherMedia from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WeatherMedia instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static WeatherMedia fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence station;
   private int tempMedia;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WeatherMedia() {}

  /**
   * All-args constructor.
   * @param station The new value for station
   * @param tempMedia The new value for tempMedia
   */
  public WeatherMedia(java.lang.CharSequence station, java.lang.Integer tempMedia) {
    this.station = station;
    this.tempMedia = tempMedia;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return station;
    case 1: return tempMedia;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: station = (java.lang.CharSequence)value$; break;
    case 1: tempMedia = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'station' field.
   * @return The value of the 'station' field.
   */
  public java.lang.CharSequence getStation() {
    return station;
  }


  /**
   * Sets the value of the 'station' field.
   * @param value the value to set.
   */
  public void setStation(java.lang.CharSequence value) {
    this.station = value;
  }

  /**
   * Gets the value of the 'tempMedia' field.
   * @return The value of the 'tempMedia' field.
   */
  public int getTempMedia() {
    return tempMedia;
  }


  /**
   * Sets the value of the 'tempMedia' field.
   * @param value the value to set.
   */
  public void setTempMedia(int value) {
    this.tempMedia = value;
  }

  /**
   * Creates a new WeatherMedia RecordBuilder.
   * @return A new WeatherMedia RecordBuilder
   */
  public static com.mcherubini.WeatherMedia.Builder newBuilder() {
    return new com.mcherubini.WeatherMedia.Builder();
  }

  /**
   * Creates a new WeatherMedia RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WeatherMedia RecordBuilder
   */
  public static com.mcherubini.WeatherMedia.Builder newBuilder(com.mcherubini.WeatherMedia.Builder other) {
    if (other == null) {
      return new com.mcherubini.WeatherMedia.Builder();
    } else {
      return new com.mcherubini.WeatherMedia.Builder(other);
    }
  }

  /**
   * Creates a new WeatherMedia RecordBuilder by copying an existing WeatherMedia instance.
   * @param other The existing instance to copy.
   * @return A new WeatherMedia RecordBuilder
   */
  public static com.mcherubini.WeatherMedia.Builder newBuilder(com.mcherubini.WeatherMedia other) {
    if (other == null) {
      return new com.mcherubini.WeatherMedia.Builder();
    } else {
      return new com.mcherubini.WeatherMedia.Builder(other);
    }
  }

  /**
   * RecordBuilder for WeatherMedia instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WeatherMedia>
    implements org.apache.avro.data.RecordBuilder<WeatherMedia> {

    private java.lang.CharSequence station;
    private int tempMedia;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mcherubini.WeatherMedia.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.station)) {
        this.station = data().deepCopy(fields()[0].schema(), other.station);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.tempMedia)) {
        this.tempMedia = data().deepCopy(fields()[1].schema(), other.tempMedia);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing WeatherMedia instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mcherubini.WeatherMedia other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.station)) {
        this.station = data().deepCopy(fields()[0].schema(), other.station);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tempMedia)) {
        this.tempMedia = data().deepCopy(fields()[1].schema(), other.tempMedia);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'station' field.
      * @return The value.
      */
    public java.lang.CharSequence getStation() {
      return station;
    }


    /**
      * Sets the value of the 'station' field.
      * @param value The value of 'station'.
      * @return This builder.
      */
    public com.mcherubini.WeatherMedia.Builder setStation(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.station = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'station' field has been set.
      * @return True if the 'station' field has been set, false otherwise.
      */
    public boolean hasStation() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'station' field.
      * @return This builder.
      */
    public com.mcherubini.WeatherMedia.Builder clearStation() {
      station = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'tempMedia' field.
      * @return The value.
      */
    public int getTempMedia() {
      return tempMedia;
    }


    /**
      * Sets the value of the 'tempMedia' field.
      * @param value The value of 'tempMedia'.
      * @return This builder.
      */
    public com.mcherubini.WeatherMedia.Builder setTempMedia(int value) {
      validate(fields()[1], value);
      this.tempMedia = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'tempMedia' field has been set.
      * @return True if the 'tempMedia' field has been set, false otherwise.
      */
    public boolean hasTempMedia() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'tempMedia' field.
      * @return This builder.
      */
    public com.mcherubini.WeatherMedia.Builder clearTempMedia() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WeatherMedia build() {
      try {
        WeatherMedia record = new WeatherMedia();
        record.station = fieldSetFlags()[0] ? this.station : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.tempMedia = fieldSetFlags()[1] ? this.tempMedia : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WeatherMedia>
    WRITER$ = (org.apache.avro.io.DatumWriter<WeatherMedia>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WeatherMedia>
    READER$ = (org.apache.avro.io.DatumReader<WeatherMedia>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.station);

    out.writeInt(this.tempMedia);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.station = in.readString(this.station instanceof Utf8 ? (Utf8)this.station : null);

      this.tempMedia = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.station = in.readString(this.station instanceof Utf8 ? (Utf8)this.station : null);
          break;

        case 1:
          this.tempMedia = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










